tasks:
  - init: pip install -r requirements.txt
  - command: gp open Lecture_1.ipynb

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers